/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.LoaiSanPhamDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.border.EtchedBorder;
import modal.LoaiSanPham;
import utils.MsgBox;

/**
 *
 * @author DELL
 */
public class LoaiSanPhamForm extends javax.swing.JDialog {

    /**
     * Creates new form LoaiSanPham
     */
    LoaiSanPhamDAO lspDAO;
    LoaiSanPham lsp;
    List<LoaiSanPham> lstLSP;
    EtchedBorder eb;
    public LoaiSanPhamForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Loại sản phẩm");
        initErr();
        eb = new EtchedBorder(Color.red, Color.white);
    }
    public LoaiSanPham getForm() {
        LoaiSanPham lsp = new LoaiSanPham();
        lsp.setTenLoaiSP(txtName.getText());
        return lsp;
    }
    public void initErr() {
        txtName.setBorder(new javax.swing.JTextField().getBorder());
        lblErrName.setText(null);
    }
    public boolean validateEmpty() {
        boolean isValid = true;
        if(txtName.getText().equals("")) {
            txtName.setBorder(eb);
            lblErrName.setText("Vui lòng nhập trường này");
            lblErrName.setForeground(new java.awt.Color(204,51,0));
            isValid = false;
            return isValid;
        }
        // Kiểm tra xem loại sản phẩm đã tồn tại hay chưa
        lspDAO = new LoaiSanPhamDAO();
        lstLSP = new ArrayList<>();
        lstLSP = lspDAO.checkProductEmpty(txtName.getText());
        if(!lstLSP.isEmpty()) {
            txtName.setBorder(eb);
            lblErrName.setText("Đã tồn tại loại sản phẩm này");
            lblErrName.setForeground(new java.awt.Color(204,51,0));
            isValid = false;
        }
        
        return isValid;
    }
    public void insert() {
        if(validateEmpty()) {
            lspDAO = new LoaiSanPhamDAO();
            int rowEffect = lspDAO.insert(this.getForm());
            if(rowEffect > 0) {
                initErr();
                txtName.setText(null);
                ThongBaoForm tb = new ThongBaoForm(null, true);
                tb.setMessage("Thêm sản phẩm thành công");
                tb.setVisible(true);
            }       
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblErrName = new javax.swing.JLabel();
        btnAdd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tên loại sản phẩm");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 240, 40));

        lblErrName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblErrName.setText("Error Message");
        jPanel1.add(lblErrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 240, -1));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn-add2.png"))); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg-kindProduct.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
       insert();
    }//GEN-LAST:event_btnAddMouseClicked

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        initErr();
    }//GEN-LAST:event_txtNameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoaiSanPhamForm dialog = new LoaiSanPhamForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblErrName;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
