/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Window;
import java.awt.event.KeyEvent;
import javax.swing.border.LineBorder;
import utils.Validator;
import utils.XImg;

/**
 *
 * @author DELL
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Đăng Nhập");
        this.setBackground(new java.awt.Color(0,0,0,0));
        pnlLayOut.setBackground(new java.awt.Color(0,0,0,0));
        initError();
        setIconImage(XImg.logoApp());
    }
    public void initError() {
        lblErrUser.setText(null);
        lblErrPw.setText(null);
    }
    public boolean validateAll() {
        boolean isFormValid = true;
        if(Validator.isEmptyUser(txtUser, txtPw, lblErrUser, lblErrPw)) {
            isFormValid = false;
        }
        return isFormValid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLayOut = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPw = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPw = new javax.swing.JPasswordField();
        lblErrUser = new javax.swing.JLabel();
        lblErrPw = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblForgotPw = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        pnlLayOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        lblTitle.setText("ĐĂNG NHẬP");
        pnlLayOut.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblUser.setText("Tài khoản");
        pnlLayOut.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        lblPw.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblPw.setText("Mật khẩu");
        pnlLayOut.add(lblPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        txtUser.setBackground(new java.awt.Color(245, 245, 245));
        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
        });
        pnlLayOut.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 210, 40));

        txtPw.setBackground(new java.awt.Color(245, 245, 245));
        txtPw.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPwKeyPressed(evt);
            }
        });
        pnlLayOut.add(txtPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 210, 40));

        lblErrUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblErrUser.setText("Error Message");
        pnlLayOut.add(lblErrUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 210, -1));

        lblErrPw.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblErrPw.setText("Error Message");
        pnlLayOut.add(lblErrPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 210, -1));

        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn-login.png"))); // NOI18N
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });
        pnlLayOut.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 170, 50));

        lblForgotPw.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblForgotPw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForgotPw.setText("Quên mật khẩu?");
        pnlLayOut.add(lblForgotPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 150, -1));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        pnlLayOut.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 30, 20));

        lblBG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background-login4.png"))); // NOI18N
        pnlLayOut.add(lblBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 600, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLayOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLayOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        txtUser.setBackground(Color.white);
        lblErrUser.setText(null);
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtPwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPwKeyPressed
        txtPw.setBackground(Color.white);
        lblErrPw.setText(null);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(validateAll()) {
                this.dispose();
                new MainForm().setVisible(true);
            }
        }
    }//GEN-LAST:event_txtPwKeyPressed

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        if(validateAll()) {
            this.dispose();
            new MainForm().setVisible(true);
        }
    }//GEN-LAST:event_lblLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblErrPw;
    private javax.swing.JLabel lblErrUser;
    private javax.swing.JLabel lblForgotPw;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPw;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlLayOut;
    private javax.swing.JPasswordField txtPw;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
