/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import javax.swing.border.EtchedBorder;
import utils.Auth;
import utils.MsgBox;

/**
 *
 * @author DELL
 */
public class SoLuongSP extends javax.swing.JDialog {

    /**
     * Creates new form SoLuongSP
     */
    public SoLuongSP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Số lượng mua");
        initErr();
    }
    public void initErr() {
        lblErr.setText(null);
        txtQuantity.setBorder(new javax.swing.JTextField().getBorder());
    }
    public boolean validateEmpty() {
        boolean isValid = true;
        String pattern = "\\d+";
        EtchedBorder eb = new EtchedBorder(Color.red, Color.white);
        if(txtQuantity.getText().equals("")) {
            txtQuantity.setBorder(eb);
            lblErr.setText("Vui lòng nhập trường này");
            lblErr.setForeground(new java.awt.Color(255,102,102));
            isValid = false;
            return isValid;
        }
        if(!txtQuantity.getText().matches(pattern)) {
            txtQuantity.setBorder(eb);
            lblErr.setText("Vui lòng không nhập chữ");
            lblErr.setForeground(new java.awt.Color(255,102,102));
            isValid = false;
        }
        return isValid;
        
    }
    public void confirm() {
            if(validateEmpty()) {
                int getQuantity = Integer.parseInt(txtQuantity.getText());
                Auth.soLuong = getQuantity;
                this.dispose();                               
            }            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtQuantity = new javax.swing.JTextField();
        btnYes = new javax.swing.JButton();
        lblErr = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantityFocusLost(evt);
            }
        });
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
        });
        jPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 190, 50));

        btnYes.setBackground(new java.awt.Color(255, 255, 255));
        btnYes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnYes.setText("XÁC NHẬN");
        btnYes.setBorder(null);
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });
        jPanel1.add(btnYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 124, 40));

        lblErr.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblErr.setForeground(new java.awt.Color(255, 102, 102));
        lblErr.setText("Error Message");
        jPanel1.add(lblErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SỐ LƯỢNG SẢN PHẨM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 20, 140, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg-quantity.jpg"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        confirm();
    }//GEN-LAST:event_btnYesActionPerformed

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
       initErr();
    }//GEN-LAST:event_txtQuantityKeyPressed

    private void txtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusLost
        validateEmpty();
    }//GEN-LAST:event_txtQuantityFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoLuongSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoLuongSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoLuongSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoLuongSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SoLuongSP dialog = new SoLuongSP(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblErr;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
